# Data Cleaning in Pandas - Introduction

## Introduction

In this section, you will learn invaluable skills that will form the foundation of your data processing work. Before you can apply machine learning algorithms or do interesting analyses, you often must clean and transform your data into a suitable format. Such initial data wrangling processes are often referred to as Extract Transform Load (ETL). Our primary tool of choice for performing ETL and basic analyses will be the Pandas package.

## Why ETL?

ETL is an essential first step to data analysis and data science. It also will form the foundation for exploratory data analysis. Often, you will be thrown a dataset that you have little to no information about. In these cases, your first step is to explore the data and get familiar with it. What are the columns? How many observations do you have? Are there missing values? Any outliers? If we have user-level data, how can we explore aggregate trends along features like gender, race, or geography? All of these can be answered by applying ETL to transform raw datasets into alternative useful views.

#ETL
* Extract
* Transform
* Load - relational, non relational (relational== mysql, nonrelational== text images, mongodb,)

## Quick ETL Example

While you'll see complete examples and explanations for all of these techniques (and more), here's a quick preview of some ETL techniques covered in this section.

### Import data

In [4]:
import pandas as pd # load pandas library
df = pd.read_csv('Yelp_Reviews.csv', index_col=0) # read the csv file
df.head()

,business_id,cool,date,funny,review_id,stars,text,useful,user_id
1,pomGBqfbxcqPv14c3XH-ZQ,0,2012-11-13,0,dDl8zu1vWPdKGihJrwQbpw,5,I love this place! My fiance And I go here atl...,0,msQe1u7Z_XuqjGoqhB0J5g
2,jtQARsP6P-LbkyjbO1qNGg,1,2014-10-23,1,LZp4UX5zK3e-c5ZGSeo3kA,1,Terrible. Dry corn bread. Rib tips were all fa...,3,msQe1u7Z_XuqjGoqhB0J5g
4,Ums3gaP2qM3W1XcA5r6SsQ,0,2014-09-05,0,jsDu6QEJHbwP2Blom1PLCA,5,Delicious healthy food. The steak is amazing. ...,0,msQe1u7Z_XuqjGoqhB0J5g
5,vgfcTvK81oD4r50NMjU2Ag,0,2011-02-25,0,pfavA0hr3nyqO61oupj-lA,1,This place sucks. The customer service is horr...,2,msQe1u7Z_XuqjGoqhB0J5g
10,yFumR3CWzpfvTH2FCthvVw,0,2016-06-15,0,STiFMww2z31siPY7BWNC2g,5,I have been an Emerald Club member for a numbe...,0,TlvV-xJhmh7LCwJYXkV-cg

In [7]:
df.shape

(2610, 9)

In [ ]:
#print # of rows
print(f'the number of rows )

### Apply lambda functions

In [8]:
df['Review_Word_Length'] = df['text'].map(lambda x: len(x.split()))
df.head()

,business_id,cool,date,funny,review_id,stars,text,useful,user_id,Review_Word_Length
1,pomGBqfbxcqPv14c3XH-ZQ,0,2012-11-13,0,dDl8zu1vWPdKGihJrwQbpw,5,I love this place! My fiance And I go here atl...,0,msQe1u7Z_XuqjGoqhB0J5g,58
2,jtQARsP6P-LbkyjbO1qNGg,1,2014-10-23,1,LZp4UX5zK3e-c5ZGSeo3kA,1,Terrible. Dry corn bread. Rib tips were all fa...,3,msQe1u7Z_XuqjGoqhB0J5g,30
4,Ums3gaP2qM3W1XcA5r6SsQ,0,2014-09-05,0,jsDu6QEJHbwP2Blom1PLCA,5,Delicious healthy food. The steak is amazing. ...,0,msQe1u7Z_XuqjGoqhB0J5g,30
5,vgfcTvK81oD4r50NMjU2Ag,0,2011-02-25,0,pfavA0hr3nyqO61oupj-lA,1,This place sucks. The customer service is horr...,2,msQe1u7Z_XuqjGoqhB0J5g,82
10,yFumR3CWzpfvTH2FCthvVw,0,2016-06-15,0,STiFMww2z31siPY7BWNC2g,5,I have been an Emerald Club member for a numbe...,0,TlvV-xJhmh7LCwJYXkV-cg,32

In [6]:
df.shape # Previously this was (2610, 9), now we have added a column

(2610, 9)

In [7]:
df.columns

Index(['business_id', 'cool', 'date', 'funny', 'review_id', 'stars', 'text',
       'useful', 'user_id'],
      dtype='object')

In [8]:
df['text']

1       I love this place! My fiance And I go here atl...
2       Terrible. Dry corn bread. Rib tips were all fa...
4       Delicious healthy food. The steak is amazing. ...
5       This place sucks. The customer service is horr...
10      I have been an Emerald Club member for a numbe...
                              ...
689     Came here with my 2 year old daughter for our ...
4874    Great little restaurant. Not to many tables an...
564     Always great friendly service and fresh baked ...
3458    We were expecting amazing Thai food after all ...
4206    Sunday at 8p. Not many people here at all. We ...
Name: text, Length: 2610, dtype: object

In [12]:
pd.set_colwidth()

AttributeError: module 'pandas' has no attribute 'set_colwidth'

In [15]:
pd.set_option('display.max_colwidth', None)

In [16]:
df['text'] # to read entire sentence

1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               I love this place! My fiance And I go here atleast once a week. The portions are huge! Food is amazing. I love their carne asada. They have great lunch specials... Leticia is super nice and cares about what you think of her restaurant. You have to try their cheese enchiladas too the sauce is different And amazing!!!
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Terrible. Dry corn bread. Rib tips were all fat and mushy and had no flavor. If you want bbq in this neighborhood go to john mulls roadkill grill. Trust me.
4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Delicious healthy food. The steak is amazing. Fish and pork are awesome too. Service is above and beyond. Not a bad thing to say about this place. Worth every penny!
5                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         This place sucks. The customer service is horrible. They dont serve food unless you order a pizza from a neighboring restaurant. Who does that? They dont control their crowd. Many times I've gone I've seen fights. The bartenders suck - I've almost got in a fight with one because she was a complete bitch. Refused to serve me a drink because she was "busy" celebrating her friends birthday BEHIND THE BAR. This place is ridiculous. I will NEVER go there again.. EVER.
10                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  I have been an Emerald Club member for a number of years.  I have always been very satisfied with their vehicles and customer service.  This recent visit to Pittsburgh was no exception.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ...
689                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               Came here with my 2 year old daughter for our first date last night.  Halfway through the movie she got tired ad wanted to go home and when the front desk saw us leave, she asked if everything was ok.  We old her what happened and she gave us 2 free passes to come back again!  Awesome!  Clean place, great seating!
4874                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 Great little restaurant. Not to many tables and its byob, which is awesome. We had the Pad Thai and the coconut curry noodles and it was absolutely fantastic. I would absolutely recommend this on a cool day when you want to warm up!
564                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Always great friendly service and fresh baked bread and desserts everyday. \r\n\r\nHighly recommend the custard cakes they are the closest thing I have ever tried to the original Pastéis de Belém in Lisboa  \r\n\r\nThe rice flour cake is also really good and a good option for those whom do not like cake too sweet. \r\n\r\n\r\nThe bean cakes are great here too!  orange, almond, and a few others I have tried are all good. \r\n\r\n\r\nCan't go wrong with Nova Era
3458    We were expecting amazing Thai food after all the reviews that we read and the fact that this place was voted one of the top 100 restaurants in Toronto. \r\n\r\nThis was disappointing. \r\n\r\nFirst off, it was really awkward sitting on the benches outside on the sidewalk, as people walked past us while to wait for our table. \r\n\r\nSecond, when we were seated, it was so loud. It felt like we were in a high school cafeteria. There was so much noise from people talking over each other and from the loud music. We were just happy that we didn't have to share a table with another couple. \r\n\r\nFinally - Food was mediocre. I was extremely disappointed with the curry egg noodle dish. It was awkward to eat and I felt sick about half way through because the curry was too rich. On the flip side - I had a taste of my company's dish and it wasn't that great either - he had the beef stir fry dish with rice. The meat was nice and tender, but it wasn't flavourful. \r\n\r\nWasn't worth the hype, unfortunately.
4206                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Sunday at 8p. Not many people here at all. We were seated for 10-15 min, and no one came to take our drink order. We were nicely greeted at the front though. Guess there was a disconnect between the hostess and waitstaff.
Name: text, Length: 2610, dtype: object

In [14]:
for x in ['']

ValueError: Must provide an even number of non-keyword arguments

### Group data

In [17]:
df.groupby('business_id')['stars'].mean().head()

business_id
-050d_XIor1NpCuWkbIVaQ    5.0
-0qht1roIqleKiQkBLDkbw    1.0
-3zffZUHoY8bQjGfPSoBKQ    5.0
-6tvduBzjLI1ISfs3F_qTg    5.0
-9nai28tnoylwViuJVrYEQ    5.0
Name: stars, dtype: float64

In [18]:
df['useful']

1       0
2       3
4       0
5       2
10      0
       ..
689     2
4874    0
564     0
3458    1
4206    0
Name: useful, Length: 2610, dtype: int64

In [24]:
#determine the average for useful column by user id (by implies group by)
#df.groupby('useful')['user_id'].mean().head()
#df.groupby('user_id')['useful'].mean().head(3)
df.groupby('user_id')['useful'].mean() # dataframe

user_id
-0biHfjE0soSptbU5G3nug    0.0
-2K0yp7lBT_JUOzGkpdJ_g    0.0
-Opvc9hAWllZSSPDUsD7NA    0.0
-Zdxj4wuj4D_899B7tPE3g    0.0
-_iULENf28RbqL2k0ja5Xw    0.0
                         ...
zdG-3ABz7-mv1P3cs2_Rfg    0.0
zpQ76JRDkleW-RQ-U__83g    0.0
zr3d9JdYSBJ0fIJefOqOsQ    0.0
zxCJAztRkzw4kDBxpwKWWg    0.0
zx_Op2OAOM_fRic9tU-jqA    0.0
Name: useful, Length: 1010, dtype: float64

### Check for duplicates

Check how many we have:

In [26]:
df.duplicated().value_counts() #2277 aint dup 333 are dup

False    2277
True      333
dtype: int64

Visually inspect them:

In [28]:
df[df.duplicated()]

,business_id,cool,date,funny,review_id,stars,text,useful,user_id
4252,fIuquIgWrkNEM5yvYSHPgw,2,2014-08-05,0,X4glBKsOvs6fgjHNJ0IUjw,5,What a compassionate and thorough professional. Our family had the pleasure of meeting Dr. Gilchrist and his associate Alex today when they came by to assess our 14 year old dog. This was such a positive experience for our dog to be examined in the security of her home. We were given plenty of opportunities to ask any questions and our questions were thoroughly answered. We will definitely call Dr. Gilchrist again.,3,xDjaGtx-TZUDdUxRKJnKCA
3028,_JD_U3pZDynB6l8swzVlQA,0,2017-12-17,0,iuVHqEglBCmL1lAbw8B2Ow,5,Had to switch barbers because I moved and the place I used to go to didn't take appointments. Great old school barber shop that does the straight razor finish. You can make appointments online which is really convenient especially since I work a lot and don't have a lot of free time. Boris always cuts my hair and is great at what he does and also consistent. I never have to worry if it's going to be a good haircut and I'm kind of ocd about haircuts. I would definitely recommend this place.,0,WBKGxL53Tcq2_CkPavBYQA
3046,yQUXMWSA8H7wvkLa4iCD8g,0,2014-08-28,0,KmKCR_cHmAYA12Uy3XPHCA,2,Rude waitress and slow service. No offers for upgrades like cheese on pasta or check ins on the food. Paper menu doubles as the placemat and you must seat yourself as well as add your own condiments one little packet at a time. Water was warm and waiters stood around chatting while our cups were empty. When tip was low due to mutiple failings the waitress thought it was her duty to advise us she expected 15% regardless.,1,KeYB7tU5F5PFb7X1QoWJ6Q
2322,1lLJDy73uBp_I2LJ0B0Fkw,1,2011-09-09,0,03dNKEDriDeZ8poYbiNyxQ,5,Was here for a party last weekend and had a blast. They play great Jazz music on Sundays and the tapas are really amazing. Would highly recommend.,0,ftLmo96CeyaNcVqHleDSHw
794,XXW_OFaYQkkGOGniujZFHg,0,2013-12-04,0,XxsMdJl8OTgeq5iEhp4JLQ,5,this is for the fireside lounge.\r\ngreat place to finish the night off or start it. the appetizers were large portions and the well drinks were also great. it has a old las Vegas feel to it,1,D1_nrBr4dOrs7M82OaBRwQ
...,...,...,...,...,...,...,...,...,...
1668,BPyopyEntbl4obte91gNrQ,0,2016-07-17,0,iWL20DdQRBHNWap7aPyH8g,5,I came to see the new Trader Joe's and had an excellent experience. The staff was very helpful and the store was nice and clean.,0,MmOlteGoOLp4uydXpW7EHg
2775,7sPNbCx7vGAaH7SbNPZ6oA,0,2013-08-28,0,WwsLyhbRkAVoOj7eQWNQXg,5,HANDS DOWN the best burger joint!\r\n\r\nPros:\r\n+great service\r\n+amazing food\r\n+oxtail fries\r\n+kiki burger\r\n\r\nCons:\r\n-there isn't one in San Diego!,1,M8KZG9AxSaaJCyRZrHVXzg
506,RJxkhoGxTsz545_sTlDdFA,0,2014-07-01,0,cEQ9swcZ_L0GMCKI0UtItQ,2,Pad thai (beef)\r\n- The beef used was tough and chewy. The pad thai was too saucy. Lunch special for pad thai is 6.59.,0,UGW-9bbBEB3eP1o6mWD_WA
4674,4KfDcE9iU2isFpoaKeDpgw,0,2012-06-14,0,rFH9iSvRmdm5LtDdsYwwpA,5,Great place to take your kids and interesting for adults to.,0,9gYbRvijurhrnC6yPRlaUw
4812,e13SEvJud_vgeDR_doL4sQ,0,2013-03-01,0,lUV1KEm4cl4mluSEFharFQ,4,We loved the food. The service was good and we were grateful to be seated right away. We have eaten Mexican and TexMex food while living and visiting in Texas. The food was very good and authentic.,0,NW6gHZ8PlYl1STK1A1Ixeg

In [27]:
# Use keep=False to keep all duplicates and sort_values to put duplicates next to each other
df[df.duplicated(keep=False)].sort_values(by='business_id') #find dup by business_id

,business_id,cool,date,funny,review_id,stars,text,useful,user_id
1729,-GY2fx-8udXPY8qn2HVBCg,0,2016-08-30,0,yQ6P1_CvM94wMLYw1T0UWA,5,Just opened a new account today. So far I am impressed. Nidia was able to coordinate everything via email for my loan and new account which is great with my busy schedule. They were able to get me a lower rate than I was expecting for my new car I also refinanced my current car.,1,sZfZGrI592euyacKUcwQYg
1729,-GY2fx-8udXPY8qn2HVBCg,0,2016-08-30,0,yQ6P1_CvM94wMLYw1T0UWA,5,Just opened a new account today. So far I am impressed. Nidia was able to coordinate everything via email for my loan and new account which is great with my busy schedule. They were able to get me a lower rate than I was expecting for my new car I also refinanced my current car.,1,sZfZGrI592euyacKUcwQYg
754,-LRlx2j9_LB3evsRRcC9MA,0,2017-10-07,0,kUqPsZmWwLIMSstGHhWssA,5,The vet took the time to explain what was possibly going on with my dog. Staff was friendly. Pricing was good. I will be going back for my vet needs in the future.,0,VgaYZ7004pTwEDSDWR6u4Q
754,-LRlx2j9_LB3evsRRcC9MA,0,2017-10-07,0,kUqPsZmWwLIMSstGHhWssA,5,The vet took the time to explain what was possibly going on with my dog. Staff was friendly. Pricing was good. I will be going back for my vet needs in the future.,0,VgaYZ7004pTwEDSDWR6u4Q
2767,-MKWJZnMjSit406AUKf7Pg,0,2015-01-03,2,rJhrQD3-b9GjTso0dxIkwg,1,Drove 37 miles on a Saturday at 12:30pm for lunch.... to find the place CLOSED! \r\nNOT HAPPY !!!!,0,kzP96uX8TUMmmvLtd-I3RQ
...,...,...,...,...,...,...,...,...,...
2193,zKw09ftu1730wEIZBZPoFg,3,2015-01-04,0,JV-yxKxMFp-d0rLDc_2_6w,5,So relaxing combined with the meditation and reiki. I'm still floating somewhere out in space. And breathing so much better. This was my first time and I will definitely be back.,5,3mZFkwfa6XV0BBazRTva9w
496,zg5rJfgT4jhzg1d6r2twnA,0,2014-06-21,0,Zbj0HgdN3AT4l-mbH-EfjA,3,Burger week\r\n\r\n1. Blazing Pineapple Burger ($5)\r\n- Decent burger. Good size patty and bun. Only special addition was a grilled slice of pineapple which did add a nice touch to it. The sauce was spicy and can definitely feel the kick after every bite. \r\n\r\nOverall:\r\nNot bad for a quick bite but wouldn't go out of the way to get it.,0,UGW-9bbBEB3eP1o6mWD_WA
496,zg5rJfgT4jhzg1d6r2twnA,0,2014-06-21,0,Zbj0HgdN3AT4l-mbH-EfjA,3,Burger week\r\n\r\n1. Blazing Pineapple Burger ($5)\r\n- Decent burger. Good size patty and bun. Only special addition was a grilled slice of pineapple which did add a nice touch to it. The sauce was spicy and can definitely feel the kick after every bite. \r\n\r\nOverall:\r\nNot bad for a quick bite but wouldn't go out of the way to get it.,0,UGW-9bbBEB3eP1o6mWD_WA
988,ziv21pDfyrgdhlrlNIgDfg,0,2016-08-11,0,fus9odxu9bjE2lSxfwNfdw,5,Get this!!! Wow Karlo is amazing and best customer service you could ask for. He installed the antenna and set up all our tv's along with excellent detail explanations and conversation. We will be having my moms house done now next week also. The recoup savings from not having cable is only a few months. Already feels like we are saving money.,2,ywjqPgnMrDZKOhA33v92Cw
988,ziv21pDfyrgdhlrlNIgDfg,0,2016-08-11,0,fus9odxu9bjE2lSxfwNfdw,5,Get this!!! Wow Karlo is amazing and best customer service you could ask for. He installed the antenna and set up all our tv's along with excellent detail explanations and conversation. We will be having my moms house done now next week also. The recoup savings from not having cable is only a few months. Already feels like we are saving money.,2,ywjqPgnMrDZKOhA33v92Cw

### Remove duplicates

In [29]:
df = df.drop_duplicates()
df.shape # Previously this was (2610, 10), now we have dropped duplicate rows

(2277, 9)

In [32]:
df.drop_duplicates(inplace = true)

NameError: name 'true' is not defined

### Recheck for duplicates

In [33]:
df.duplicated().value_counts()

False    2277
dtype: int64

In [15]:
# Duplicates should no longer exist
df[df.duplicated(keep=False)].sort_values(by='business_id')

Empty DataFrame
Columns: [business_id, cool, date, funny, review_id, stars, text, useful, user_id, Review_Word_Length]
Index: []

### Create pivot tables

In [34]:
# This transforms the data into a person by person spreadsheet and what stars they gave various restaurants
# Most values are NaN (null or missing) because people only review a few restaurants of those that exist
usr_reviews = df.pivot(index='user_id', columns='business_id', values='stars')
usr_reviews.head()

business_id,-050d_XIor1NpCuWkbIVaQ,-0qht1roIqleKiQkBLDkbw,-3zffZUHoY8bQjGfPSoBKQ,-6tvduBzjLI1ISfs3F_qTg,-9nai28tnoylwViuJVrYEQ,-C8sSrFqaCxp51pyo-fQLQ,-Dnh48f029YNugtMKkkI-Q,-FLnsWAa4AGEW4NgE8Fqew,-G7MPSNBpxRJmtrJxdwt7A,-GY2fx-8udXPY8qn2HVBCg,...,zdE82PiD6wquvjYLyhOJNA,zdd3hyxB8ylYV6RcNe347Q,zg5rJfgT4jhzg1d6r2twnA,ziv21pDfyrgdhlrlNIgDfg,zkhBU5qW_zCy0q4OEtIrsA,ztP466jMUMtqLwwHqXbk9w,zw9_mqWBn1QCfZg88w0Exg,zwNLJ2VglfEvGu7DDZjJ4g,zzYaAiC0rLNSDiFQlMKOEQ,zzgSiOnuUjnBnmfR-ZG4ww
user_id,,,,,,,,,,,,,,,,,,,,,
-0biHfjE0soSptbU5G3nug,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
-2K0yp7lBT_JUOzGkpdJ_g,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
-Opvc9hAWllZSSPDUsD7NA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
-Zdxj4wuj4D_899B7tPE3g,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
-_iULENf28RbqL2k0ja5Xw,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Summary

In this brief introduction, you learned the acronym ETL and got to preview a few examples of ETL processes using pandas.